### ISSUE TITLE
PHCpack

### ISSUE THREAD

**Issue by musicman3320** [musicman3320/m2r#10]
Ideal for Jeff ;)

**Comment by sommars** [comment]
What's the best way to represent points in R? I'm trying to figure out what data structure to parse into.

**Comment by dkahle** [comment]
Probably a list of numeric vectors (i.e. `list(c(1,2), c(3,4), c(5,6))`) or a matrix (`rbind(c(1,2), c(3,4), c(5,6))`).

**Comment by musicman3320** [comment]
My vote would be for the former.  Using a matrix would bother the mathematician somewhere deep in my subconscious.

**Comment by musicman3320** [comment]
To get the pathing to work correctly, in Macaulay2 you need to run `loadPackage "PHCpack"`.  The first time that is run, it generates a file `init_PHCpack.m2` that lives somewhere on your machine, depending on where your Macaulay2 is installed. That file is usually at `$HOME/.Macaulay2` as explained [here](http://www.math.uiuc.edu/Macaulay2/doc/Macaulay2-1.6/share/doc/Macaulay2/Macaulay2Doc/html/_initialization_spfile.html).

There are two ways to get M2 to know where PHCpack lives:
-The first way is to manually edit the file `init_PHCpack.m2` and set the path to phc.
-The other way is to override the value of path whenever you call `loadPackage()`. This would be done with the following command: 
```loadPackage( "PHCpack", Configuration =>{"path" => "absolute_path_of_wherever_phc_is"})```

**Comment by musicman3320** [comment]
What is the status of this?

**Comment by sommars** [comment]
It was implemented, probably just needs to be cleaned. I can do it.
