### ISSUE TITLE
Server version of M2

### ISSUE THREAD

**Issue by musicman3320** [musicman3320/m2r#107]
With very little changes, it should be possible (with very few code changes) to create a server version of the M2 script, so that users without Macaulay2 installed can query the server instead.  

Perhaps we can even run this on a public Macaulay2 server?  @sommars you likely know more about this side of things and who to contact.

**Comment by dkahle** [comment]
Have you seen this? http://habanero.math.cornell.edu:3690

**Comment by musicman3320** [comment]
My thoughts exactly :).  We should be able to piggy back off of this pretty easily, launching an M2 instance on the server rather than locally if the user desires, perhaps with help from whoever runs the server.

**Comment by musicman3320** [comment]
This may even be a better way to handle #24, since it does not require ugly workarounds (though it would be nice to also allow the diligent Windows user to connect to their local installation of M2 as well).

**Comment by sommars** [comment]
The only possible issue I see with this is that it has the potential to increase the expense of the habanero server, if people actually start using m2r.

**Comment by sommars** [comment]
Finished! Hooray
