### ISSUE TITLE
m2_matrix. parameters behave strangely

### ISSUE THREAD

**Issue by musicman3320** [musicman3320/m2r#112]
The following works as expected.  
```
snf(matrix(c(
     1,    2,    3,
     1,   34,   45,
  2213, 1123, 6543,
     0,    0,    0
), nrow = 4, byrow = TRUE))
```
On the other hand, running 
```
M <- matrix(c(
     1,    2,    3,
     1,   34,   45,
  2213, 1123, 6543,
     0,    0,    0
), nrow = 4, byrow = TRUE)
snf(M)
```
from within another function produces an error.  If this is run from the R console, it runs just fine.  @dkahle I imagine it has something to do with the fancy do.call stuff at the beginning of `snf()`.

**Comment by musicman3320** [comment]
An update: it appears the issue is at the beginning of `m2_matrix.()`.  I still think it is something to do with the fancy do.call stuff.  It works when run at the console, since the matrix `M` is then globally defined, but if its run within a function we get the error "Error in unlist(mpoly) : object 'M' not found".

**Comment by musicman3320** [comment]
For clarification, the following code errors when run in the console: 
```
myfunc <- function () {
  M <- matrix(c(
    1,    2,    3,
    1,   34,   45,
    2213, 1123, 6543,
    0,    0,    0
  ), nrow = 4, byrow = TRUE)
  
    m2_matrix(M),
}
myfunc()
```

**Comment by dkahle** [comment]
I feel sure you're right, I've been fixing bugs like this and thought I'd gotten them all.  Running the following only results in an error in the last case.  
```r

snf(matrix(c(
     1,    2,    3,
     1,   34,   45,
  2213, 1123, 6543,
     0,    0,    0
), nrow = 4, byrow = TRUE))


rm(M)
M <- matrix(c(
     1,    2,    3,
     1,   34,   45,
  2213, 1123, 6543,
     0,    0,    0
), nrow = 4, byrow = TRUE)
snf(M)


rm(M)
f <- function() {
  M <- matrix(c(
       1,    2,    3,
       1,   34,   45,
    2213, 1123, 6543,
       0,    0,    0
  ), nrow = 4, byrow = TRUE)
  snf(M)
}
f()


rm(M)
M <- matrix(c(
     1,    2,    3,
     1,   34,   45,
  2213, 1123, 6543,
     0,    0,    0
), nrow = 4, byrow = TRUE)
f <- function() {
  snf(M)
}
f()


rm(M)
M <- matrix(c(
     1,    2,    3,
     1,   34,   45,
  2213, 1123, 6543,
     0,    0,    0
), nrow = 4, byrow = TRUE)
f <- function(M) {
  snf(M)
}
f() # errors
```
But this is expected:
```r
x <- 1
f <- function(x) {
  x
}
f() # errors
```
I think you're right that the problem is in `m2_matrix()`.  Pushing a fix...
