### ISSUE TITLE
Use base_class in m2_structure somewhere in parser

### ISSUE THREAD

**Issue by dkahle** [musicman3320/m2r#121]
I've added a new argument to `m2_structure()` named `base_class`.  The purpose of the argument is to give the object other classes to look for at method dispatch.  The problem is that I don't know where  all it will need to be implemented, but I've found at least one place where it's needed but isn't.

Example.  The function to compute determinants in R is `det()`.  `det()` actually calls a different function, `determinant()`, which is actually a generic method with no `determinant.default()` to back up to; the only method it has, in fact, is `determinant.matrix()` (in __base__).  Before the last commit 0e7ea9a, this was a problem because `m2_matrix` resulted in objects of class `c("m2_matrix", "m2")`, so `determinant()` (the generic) wouldn't find `determinant.matrix()`, and `det()` would fail on matrices that otherwise should be acted upon. I imagine this kind of behavior will happen in other places, too. The fix, I thought, was just to add an additional argument to `m2_structure()` that would allow us to put "back end" classes on the structure it creates, stuff to go to after `m2`.  R example:
```r
M <- matrix(c(
   2,  4,   4,
  -6,  6,  12,
  10, -4, -16
), nrow = 3, byrow = TRUE)

class(M)
# [1] "matrix"

(m2_mat <- m2_matrix(M))
#      [,1] [,2] [,3]
# [1,]    2    4    4
# [2,]   -6    6   12
# [3,]   10   -4  -16
# M2 Matrix over ZZ[]

class(m2_mat)
# [1] "m2_matrix" "m2"        "matrix"

det(m2_mat)
# [1] -144
```

That seems to work well, but it doesn't work everywhere:
```r
(mats <- snf(M))
class(mats$P)
# [1] "m2_matrix" "m2"
```
Why isn't doesn't it have `matrix` on the end?  This illustrates the problem:
```r
det(mats$P)
# Error in UseMethod("determinant") : 
#  no applicable method for 'determinant' applied to an object of class "c('m2_matrix', 'm2')"
```

**Comment by musicman3320** [comment]
This is less an issue with the parser, and more that `m2_structure` is called in many places for the same type of object (i.e. matrix objects are constructed by  many different functions).  In particular, `m2_structure` is never called "generically" in the parser, it is always called with a specific class in mind (i.e. with a hard-coded string as the `m2_class`).  

I see a couple of options here.  One is to modify the `m2_structure` function to add a base class based on the `m2_class` provided.  The other is to make sure that every time we create a matrix (or other objects), we pass the appropriate `base_class` (I am guessing one place is missing).  Neither solution is great, but I am leaning towards the latter.  

Thoughts?

**Comment by dkahle** [comment]
I totally agree.  I think I've got it with this commit... (Just for matrices now; it's around if we need it.)
