### ISSUE TITLE
Support M2 package: Gaussian Graphical Models

### ISSUE THREAD

**Issue by musicman3320** [musicman3320/m2r#18]
Special request from Liz Gross

Download: 
http://www.shsu.edu/ldg005/software.html

**Comment by sommars** [comment]
Isn't the Gaussian Graphical Models package written for Singular?

**Comment by musicman3320** [comment]
Looks that way.  It would certainly be nice to have an easier method than R -> M2 -> Singular -> GGM.  

Luis is a good friend of mine.  I will email him (CCing both of you) to ask about the best way to incorporate his package.

**Comment by sommars** [comment]
Does M2 interface with Singular?

**Comment by musicman3320** [comment]
I thought M2 used Singular under the hood for GB computations.  Is this not the case?

**Comment by sommars** [comment]
Well, it must interface somehow, based on [this](http://www.math.uiuc.edu/Macaulay2/doc/Macaulay2-1.9/share/doc/Macaulay2/Macaulay2Doc/html/___Singular-__Factory.html). I'm not sure how mature the interface is.

**Comment by musicman3320** [comment]
This actually makes it look like only one component of Singular (namely, Singular-Factory) is incorporated into M2.  Perhaps Singular is not operating `gb` under the hood after all.  

We will see what Luis has to say.  I anticipate the email going out this evening.

**Comment by musicman3320** [comment]
Based on email from Luis, the `M2` package we are actually looking for is either `GraphicalModels` or `GraphicalModelsMLE`.  Opening #55 and marking this one invalid.
