### ISSUE TITLE
Garbage collection

### ISSUE THREAD

**Issue by dkahle** [musicman3320/m2r#21]
`rm()` will create unbound M2 objects from R's perspective.  It's probably a bad idea to overload it for `m2` objects. `m2_rm()`?

**Comment by musicman3320** [comment]
I do not think M2 allows for manual garbage collection.  Only automatic.  

[M2 Garbage Collection](http://www.math.uiuc.edu/Macaulay2/doc/Macaulay2-1.9/share/doc/Macaulay2/Macaulay2Doc/html/___G__C_spgarbage_spcollector.html)

Since there is already a function to reset M2, perhaps it is ok as is?

**Comment by dkahle** [comment]
Do `erase` or `clearAll` (is there a version of `clear`?) have relevance here?

One thing I found kind of annoying was this behavior:
```{r}
m2("x = 1")
m2("x")
gb("t^4 - x", "t^3 - y", "t^2 - z")
```
Is there a way to kill the M2 variable `x` to use it later in a different way?

**Comment by musicman3320** [comment]
This is the idea behind the optional parameter `ring`.  If a variable is used in more than one ring, this will allow the user to specify which should be used.  

There is a way to unset a variable, using the syntax `x = symbol x`.  Found this [here](http://www.math.uiuc.edu/Macaulay2/doc/Macaulay2-1.9/share/doc/Macaulay2/BeginningMacaulay2/html/), which currently has a compile error and must be viewed with Google Cache to see the whole thing.  

Did I mention I despise the M2 documentation?

**Comment by dkahle** [comment]
Hm... interesting. Something to think about.

**Comment by musicman3320** [comment]
After clearing the M2 variable with `symbol`, should we also somehow clear the R reference?
