### ISSUE TITLE
options

### ISSUE THREAD

**Issue by dkahle** [musicman3320/m2r#27]
In M2, this seems helpful

```
R = QQ[x,y,z]
options R
```

What's something in R that would be similar? `options_m2()`?

**Comment by musicman3320** [comment]
This looks promising.  A general implementation would give easier access to options `m2r` does not yet implement.

**Comment by musicman3320** [comment]
Should be a way to set these options too, I assume?

**Comment by dkahle** [comment]
In M2? I'd imagine.  Maybe the `PolynomialRing` structure in R should hold all of them; and I'm thinking about killing the `str()` method.  [Replacement functions](http://adv-r.had.co.nz/Functions.html#special-calls) in R would be useful for this, I think.

**Comment by musicman3320** [comment]
Ah, I misunderstood.  It looked like `options()` was a general construct for M2 objects, but looks like its just for rings.  

Replacement seems like a reasonable way to handle this.

**Comment by dkahle** [comment]
I think I'm near a point that I just need to learn a lot more about the M2 language.  At this point it makes sense to me to have two versions of `ring()`: one line `gb()` and one like `gb_()`... thoughts?

**Comment by musicman3320** [comment]
On second thought, I rather like the current output of `str()`.  Is there a way to do a general `str()` function for all M2 wrappers (i.e. without needing a separate implementation for each class)?

**Comment by musicman3320** [comment]
I don't quite see the benefit of having both `gb()` and `gb_()` over simply having optional parameters.  Is this standard in R?

**Comment by dkahle** [comment]
`gb_()` has a nice, standard syntax.  It cleanly takes in one vector (an mpolyList) and the other arguments.  But it's somewhat awkward, because you get calls that look like `gb_(mp(c(...)))`.  By contrast, `gb()` has nice calls like `gb("t^4 - x", "t^3 - y", "t^2 - z")`, but will have some strange behavior when you use it inside other functions due to lexical scoping issues.

For us, coding with `gb_()` internally will be easier, but for most users `gb()` will be common. Does that help?

**Comment by dkahle** [comment]
For `str()`, maybe something like `str_m2()`? In general I think it's bad practice to have special methods for `str()` because it obscures how the developer is actually implementing the object.

**Comment by musicman3320** [comment]
That makes perfect sense.  I like this paradigm.  

Do you think this is necessary for `ring()` also?  To me, the parameters won't vary as much as for `gb()`.  

Regarding `str_m2()`, I agree, lets go with this.

**Comment by musicman3320** [comment]
`str_m2()` should be easy to implement as well, since we can tell by the class attribute whether the object is in fact an M2 reference or not.

**Comment by dkahle** [comment]
For `ring()`, I don't know.  I'll just leave it as-is for now.

For `str_m2()`, yea; it'll be easy.  We'll write a generic that is analogous to `str()`, then dispatch methods based on the first class attribute (e.g. `str_m2.PolynomialRing()`).

**Comment by musicman3320** [comment]
[OptionTable](http://www.math.uiuc.edu/Macaulay2/doc/Macaulay2-1.7/share/doc/Macaulay2/Macaulay2Doc/html/___Option__Table.html)
`toString options R` seems easiest to parse.

**Comment by sommars** [comment]
```options``` isn't  specific to rings in M2. I don't know all of the objects that have them, but many do. For example, when you call ```loadPackage```, the package itself can have options associated to it.

However, these options are immutable hash tables, so as far as I know, there's no way to modify them and have the changes affect the base object.

In general, M2 distinguishes between mutable and immutable a lot (hash tables, lists, matrices...). Generally, it's possible to convert between mutable and immutable classes but it's annoying. When we use mutable lists, we run into problems with the way the output is displayed:
```
> m2("new MutableList from {1,2,3}")
[1] "MutableList{...3...}"
```

However, this is fixable when we convert back:
```
 m2("new List from new MutableList from {1,2,3}")
[1] "{1, 2, 3}"
```
Hopefully that helps.

**Comment by musicman3320** [comment]
This is very helpful.  We should implement a wrapper around the OptionTable object.  Is every immutable hashtable an OptionTable object, or are there others?  Should also implement list, etc. at the same time, since these can all be nested.

**Comment by sommars** [comment]
OptionTable inherits from immutable hash table, so there can be others. Do we want to expose OptionTables to R users? I can't imagine the benefit, though that doesn't mean that there isn't any.

**Comment by musicman3320** [comment]
Well, we should let them get and set hashmap entries, since they may be interested in some of them.  Perhaps for immutable objects, it makes sense to simply convert these into R directly, and for mutable objects, we can provide a wrapper.  It also makes sense to create, say, a named list if they call the `options()` method in M2.

**Comment by sommars** [comment]
We switched to toExternalString, so this isn't necessary
