### ISSUE TITLE
M2 ring class

### ISSUE THREAD

**Issue by musicman3320** [musicman3320/m2r#3]
Attributes: 
Reference to ring instance in M2
Coefficient ring
Variables

Also add pretty print

**Comment by musicman3320** [comment]
@dkahle please verify the object format before other wrappers are created.

**Comment by dkahle** [comment]
working on it and ring.R now; will finish on plane.

i'll also write a print method.

note that the `class()` attribute can be vector valued, so i think that these objects should have class `c("[Object name in M2]", "m2")`

**Comment by musicman3320** [comment]
Excellent!  Then I can copy your print implementation for the other data structures :).  

The proposed vector structure for `class()` is perfect.  

I will stick to m2.R for my flight, will try to address #14 and #15.
