### ISSUE TITLE
Find unused M2 variable

### ISSUE THREAD

**Issue by sommars** [musicman3320/m2r#32]
There are times when it would be nice to have a function that returns a variable name that isn't being used, so we know that we won't be overwriting user defined variable names.

**Comment by musicman3320** [comment]
We currently have `name_and_increment()` in helpers.R, which we use to name M2 objects created by the package.  I am not opposed to exporting this, if this is what you are looking for.

**Comment by sommars** [comment]
This is exactly what I was looking for. I didn't realize we already had it!
