### ISSUE TITLE
Groebner basis

### ISSUE THREAD

**Issue by musicman3320** [musicman3320/m2r#4]
Parameters: 
mpoly list
ring (optional)

Returns: 
mpoly list

**Comment by musicman3320** [comment]
Ring class now implemented.

**Comment by dkahle** [comment]
i think this is mostly complete, right? @musicman3320

**Comment by musicman3320** [comment]
Oh, looks like you already implemented the optional ring parameter.  I thought that was still missing.  You were busy yesterday!  

Will test it on my end and then close.

**Comment by dkahle** [comment]
Yea, this is what I did on my flight. I actually bought a gogo wifi hour so that I could push.  Since this is so early in the project, big changes are being made quickly.  I didn't want to have big merge conflicts... ;)

**Comment by dkahle** [comment]
Actually, let's keep this open. We need to implement a broader array of options M2 makes available.  See  the documentation for `gb` [here](http://www.math.uiuc.edu/Macaulay2/doc/Macaulay2-1.9/share/doc/Macaulay2/Macaulay2Doc/html/_gb.html).

**Comment by musicman3320** [comment]
Usually this is opened as a separate issue.  Otherwise, some issues would remain open forever when only a few minor options are not yet implemented.  This is especially true when some are tied to other issues (#6, for instance).  

In my opinion, gb works quite well and supports enough options for general usage at this point.  I am comfortable closing this issue and opening a new issue for extended functionality.

**Comment by dkahle** [comment]
Good point.
