### ISSUE TITLE
Enter emulated M2 session in R

### ISSUE THREAD

**Issue by musicman3320** [musicman3320/m2r#41]

**Comment by dkahle** [comment]
Just seeing these issues now, sorry (I tinkered with my mail options and so I haven't received any of these). Did I get this with `enter_m2()`?

**Comment by musicman3320** [comment]
Yep!  Looks good.  There are still some small things (up arrow recalls R commands not M2 commands, output doesn't perfectly match M2, etc) but these can be improved later.  I will add a separate issue.
