### ISSUE TITLE
M2 Ideal class

### ISSUE THREAD

**Issue by musicman3320** [musicman3320/m2r#6]
Attributes: 
Reference to ideal instance in M2
Ring
Generators (replace with GB after computation?)

Also add pretty print

**Comment by musicman3320** [comment]
Update gb() to (optionally) receive this instead of a list of polynomials.

**Comment by sommars** [comment]
Still need to update gb(). I'm confused by the refactoring of gb(), so does one of you want to finish that part up?

**Comment by dkahle** [comment]
I think this is done with `m2_class` in 81c2842.
