### ISSUE TITLE
Update "gb" to use "gb." convension

### ISSUE THREAD

**Issue by musicman3320** [musicman3320/m2r#78]

**Comment by dkahle** [comment]
Are `ideal()` and `ideal.()` ready for us to do this? The lists inside matrices seem strange to me... @sommars

**Comment by dkahle** [comment]
Do y'all have any thoughts on what the output of this should be?  An mpolyList, or an m2_ideal?

**Comment by musicman3320** [comment]
In my opinion, an ideal object, since this can have other attributes besides "generators".  Thoughts?

**Comment by dkahle** [comment]
Give it a try now. The c4716b0 commit cleaned up a funky evaluation problem related to dynamic scoping and `do.call()`, and added a bunch of `gb()` stuff, but it's not perfect yet. (See the examples in the documentation.)

I also added some predicate functions: `is.m2_polynomialring()` existed before, but now we have `is.m2_polynomialring_pointer()` as well, which makes overloading functions (varying inputs) much easier.  I think we probably need to go back through the functions that we've made and make sure that they accept the correct ranges of inputs that we want them to (e.g., if a ring, then it can be (1) a `m2_ring` object, (2) a `m2_pointer` object to a ring, or maybe even (3) a direct character string to get put in the spot where the `m2_code` would have the ring name; see [`gb_.()`](https://github.com/musicman3320/m2r/blob/master/R/gb.R) for an example.

**Comment by musicman3320** [comment]
I agree with this structuring.  This leads to a LOT of extra code at the beginning of each `f.` function.  There are also several new parameters we will likely want in most (if not all) `f.` functions, such as `raw_code` (I like this!), or specifying a name to use (#80).  Are there some helper functions we can define to reduce the code bloat, such as a `handle_common_dot_inputs` function?

**Comment by musicman3320** [comment]
Also, we should add a ton of test cases for functions that allow these different inputs.  Better to do this earlier rather than later.

**Comment by dkahle** [comment]
I think this is done, I'm going to close it. Feel free to re-open as appropriate.
