### ISSUE TITLE
Broken factor_n.

### ISSUE THREAD

**Issue by musicman3320** [musicman3320/m2r#81]
Code to reproduce: `factor_n.(m2.("218700"))`
@dkahle are you looking into this, or should I investigate?

**Comment by dkahle** [comment]
I'll get it, I think I broke it.

**Comment by dkahle** [comment]
Oh, no, this was broken by the `=` to `:=` change:
```r
(m2_pointer <- m2.("218700"))
# Starting M2
# M2 Pointer Object
#   ExternalString : 218700
#          M2 Name : m2o2
#         M2 Class : ZZ (Ring)
factor_n(m2_pointer, code = TRUE) # note: this now only returns code
# factor m2o2
factor_n(m2_pointer)
# Error in m2.(m2_code) : Macaulay2 Error!
m2("m2o2")
# [1] "m2rintoutval"
```
I'm checking to see if there's something I can do here...

**Comment by musicman3320** [comment]
I can fix this.  It will require a slight reworking of the `try()` statement in the M2 loop.

**Comment by dkahle** [comment]
Aha, sounds good. Then I won't look at it further!  Let me know how it goes, because I can if I need to.

**Comment by dkahle** [comment]
This was fixed with an earlier commit.
