### ISSUE TITLE
mpoly parse issue?

### ISSUE THREAD

**Issue by sommars** [musicman3320/m2r#91]
Is there some reason that mpoly doesn't like the variable name e? When I run mp("e-a") mpoly seems to hang.

**Comment by musicman3320** [comment]
Oddly enough, `mp("e")` and `mp("a")` and `mp("e - a")` run as expected, but `mp("e-a")` hangs.  @dkahle any ideas on what is happening here?

**Comment by sommars** [comment]
I assume it's something to do with the "e" being used in scientific notation? This brings up a bigger issue: variable names that M2 accepts that mpoly does not.

**Comment by musicman3320** [comment]
Lucky for us, we are in pretty close contact with the author of mpoly ;).  

@dkahle what sorts of things does mpoly not accept as variable names?  Are underscores allowed?  What about single quotes?

**Comment by dkahle** [comment]
Underscores, yes. Single quotes, no. I imagine Jeff is right; I'll look into it.

**Comment by dkahle** [comment]
Ok, this is now fixed in [__mpoly__](https://github.com/dkahle/mpoly). To install the fixed version, use:
```r
devtools::install_github("dkahle/mpoly")
```
