### ISSUE TITLE
Matrix doesn't work with polynomials

### ISSUE THREAD

**Issue by sommars** [musicman3320/m2r#92]
Polynomial entries don't throw errors, but the output is not correct. It seems like something with the parser is broken? After looking at it for a while, I don't see what's wrong, otherwise I'd fix it myself.

**Comment by musicman3320** [comment]
I see the issue.  It's a greedy unlist() call on the matrix also unlisting mpolys.  Should be fixed shortly.

**Comment by musicman3320** [comment]
For reference, the following seems to help in this situation: 
`unlist(x[[3]], recursive=FALSE)`

**Comment by musicman3320** [comment]
Fixed.   Feel free to reopen if it is still broken.

**Comment by musicman3320** [comment]
Now its broken for integers.  There is a weird list vs not list thing that is happening here.  Reopening so @dkahle can show it some love.

**Comment by dkahle** [comment]
Was this referring to the line in ideal? If so, I think I fixed it.  The issue was that you had a list in a matrix object and we `lapply()`'ing it, which (short answer) doesn't work.  Ideal works now for polynomials, does it work from your side? (I will probably re-work the print method...)

**Comment by sommars** [comment]
Right now it seems to be working for integers but not polynomials. For example, this doesn't work `matrix_m2(matrix(c(mp("x")), nrow = 1, ncol = 1))`

**Comment by dkahle** [comment]
This is fixed with 16b4609; we'll reopen if it pops up again.
