### ISSUE TITLE
Name attribute returned by m2_parse

### ISSUE THREAD

**Issue by musicman3320** [musicman3320/m2r#93]
When called with an `m2_pointer` parameter, `m2_parse()` should, after parsing, set the `m2_name` attribute of the returned value if it makes sense.  In particular, if `m2_parse()` results in an `m2_matrix` or an `m2_polynomialring` then the `m2_name` attribute should match that of the input `m2_pointer`.

**Comment by musicman3320** [comment]
Added code for this but left it commented.  Breaks a lot of the unit tests for he silly reason that the names don't match.  Ideas on how to work around this?

**Comment by sommars** [comment]
I must be missing something obvious. Couldn't we just fix the unit tests?

**Comment by musicman3320** [comment]
I guess we could, to simply not check the `m2_name` attribute.  I meant that it would be hard to reliably check the m2_name attribute since the number will jump around so much, but I guess we dont need to check that it matches perfectly, maybe just that its not `NULL` or something.

**Comment by sommars** [comment]
Well, if it's a feature that we want, and the only reason we're considering not including it is that it breaks the unit tests, then we should include the feature and hack the unit tests together

**Comment by musicman3320** [comment]
Agreed.  I am in the process of revamping the unit tests to consistently check the `m2_name` attribute.
