### ISSUE TITLE
m2_parser

### ISSUE THREAD

**Issue by dkahle** [musicman3320/m2r#96]
`test-m2_to_r.R` is failing at lines 35, 40, and 75, having to deal with parsing matrices.  I think this maybe due to changes in `listify_mat()`. Thoughts?
Note: `listify_mat()` previously took a matrix A in R and created the M2 code to create the matrix A'. This has been fixed so that it now properly makes the code for A.

**Comment by musicman3320** [comment]
Just fixed the tests at lines 35 and 40.  We added a "ring" attribute that it wasn't looking for.  

I don't understand what is happening in line 75.  It looks like it is supposed to test the ideal code, but nowhere does it actually create an ideal...

**Comment by musicman3320** [comment]
Looks like @sommars fixed the one on line 75.
